name: Deploy Memo Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script: |
            export PATH=$HOME/.nvm/versions/node/v22.22.0/bin:$PATH
            cd ~/htdocs/memo-nextjs-prisma

            echo "[Step 1] 소스 코드 최신화"
            git fetch origin main
            git reset --hard origin/main

            echo "[Step 2] 의존성 및 Prisma 최신화"
            pnpm install --frozen-lockfile
            pnpm dlx prisma generate

            echo "[Step 3] Build & Server Reload"
            pnpm build
            pm2 reload memo --update-env
